### PR TITLE
WIP:allow new content to be imported without having an ID nor UUID.

### PR DESCRIPTION
**Pull request by b4oshany**
Touches #9, allow new content to be imported without having an ID nor UUID.

New content must have a path.

### CODE REVIEW

**Comment by b4oshany** [comment]
Not sure why Github is showing all of the file content as a diff, but this is what I had added:

image

**Comment by djay** [comment]
@b4oshany you need to work out why the diff is having a problem. Check line ending settings.

**Comment by djay** [comment]
@b4oshany using the os.sep doesn't seem right

**Comment by djay** [comment]
paths are always '/' in zope.

**Comment by b4oshany** [comment]
@djay `os.sep` is everywhere, that's basically how the code was initially written. I'm just following the format.

**Comment by b4oshany** [comment]
It seems like it is due to my editor. Even if I change a single letter, the entire file is diffed `git diff`. I'm not sure if it is trimming white space or what. I'm using [c9](https://c9.io/dashboard.html)

**Comment by djay** [comment]
there is some kind of global git setting to specify the line endings but I didn’t it so long ago.

**Comment by djay** [comment]
> @djay `os.sep` is everywhere, that's basically how the code was initially written. I'm just following the format.

I'll raise a new ticket then because its very wrong.

**Pull request closed without merging**
