### PR TITLE
Quang/improve import export path relation

### PR DESCRIPTION
**Pull request by nngu6036**

### CODE REVIEW

**Comment by ironmaniiith** [comment]
@djay please look into it. I've fixed the merge conflicts

**Comment by ironmaniiith** [comment]
@djay I think the PR is in a stable and mergable state now. I've fixed some other errors that were there and also added missing dependencies.
For obtaining output of the failing tests, I've done it in a rather hacky way, so if you have any better suggestion I can incorporate that, else in my opinion, we can merge this PR

**Comment by ironmaniiith** [comment]
@djay , could you please have a look.

**Comment by djay** [comment]
yes I'll merge it because the master is worse.

**Comment by ironmaniiith** [comment]
I'll sync #47 with master

**Comment by ironmaniiith** [comment]
Done, please review

**Comment by Shriyanshagro** [comment]
@ironmaniiith can you write a short description of this PR. That would be helpful to review. Make sure you do not miss anything

**Comment by djay** [comment]
The basic idea of this PR was that in your original code there was an inconsistancy between the path in the export and the import. Instead this makes all exports use a relative path and imports can use either relative or absolute url but the absolute url should be from the portal root, not the zope root as it was before.

**Pull request merged**
